#!/bin/bash

versions="2.23 2.24 2.26 2.27 2.28 2.29 2.30 2.31 2.32 2.33 2.34 2.35 2.36 2.37 2.38"

for version in ${versions}
do
    wget "https://launchpad.net/ubuntu/+archive/primary/+files/glibc_${version}.orig.tar.xz"
    tar xf "./glibc_${version}.orig.tar.xz"
done
